name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
#      run: ./gradlew build

#    - name: Print Hello World
#      run: echo "Hello World"
    - name: output path safe  #unsafe repository 오류로 일단 넣어 본다.
      run: git config --global --add safe.directory /github/workspace
    - name: Upload test APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk # 폴더로 하니깐 일단 pass가 되었다!
#          앱 FB로 특정 그룹에게 전달
    - name: delivery to Firebase App Distrubtion
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.3 # Action version 오류로 1.3.3으로 변경
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: qa
        file: app/build/outputs/apk/debug/**.apk

  unit_test_job:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: JUnit Test
      run: ./gradlew testDebugUnitTest
    - name: Update Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-report
        path: app/build/reports/

  ui_test_job:
    runs-on: macos-latest
    strategy:
        matrix:
          api-level: [ 29 ] # AVD TCP Connection 오류로 낮음.

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          emulator-build: 7425822  # AVD TCP Connection 오류로 추가함.
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
      - name: Upload Ui Test Result
        #if: ${{always()}} # JOB이 여러개가 있다면 상위 Job이 성공 하였는지 condition을 체크
        uses: actions/upload-artifact@v3
        with:
            name: ui-test-report
            path: app/build/reports/